name: Keep App Alive

on:
  schedule:
    # Runs every 12 hours (at 00:00 and 12:00 UTC)
    - cron: '0 */12 * * *'
  workflow_dispatch: # Allows manual trigger from GitHub UI

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit App
        run: |
          curl -I -s https://deeplearningproject-z7dmd9tamuvqvwexqod2pk.streamlit.app/
